//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSoft.TemperatureChart {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DCTimeLineStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DCTimeLineStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = DCSoft.Common.SafeCreateResourceManager.Create("DCSoft.TemperatureChart.DCTimeLineStrings", typeof(DCTimeLineStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消数据编辑 的本地化字符串。
        /// </summary>
        internal static string CancelEditValuePoint {
            get {
                return ResourceManager.GetString("CancelEditValuePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是第一个位置了，不能向前移动位置。 的本地化字符串。
        /// </summary>
        internal static string CannotMoveForward {
            get {
                return ResourceManager.GetString("CannotMoveForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是最后的位置，不能向后移动位置了。 的本地化字符串。
        /// </summary>
        internal static string CannotMoveNext {
            get {
                return ResourceManager.GetString("CannotMoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灯笼数据 的本地化字符串。
        /// </summary>
        internal static string DefaultLanternValueTitle {
            get {
                return ResourceManager.GetString("DefaultLanternValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除数据点 的本地化字符串。
        /// </summary>
        internal static string DeleteValuePoint {
            get {
                return ResourceManager.GetString("DeleteValuePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档全局配置 的本地化字符串。
        /// </summary>
        internal static string DocumentConfig {
            get {
                return ResourceManager.GetString("DocumentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贴图 的本地化字符串。
        /// </summary>
        internal static string DocumentImage {
            get {
                return ResourceManager.GetString("DocumentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本标签 的本地化字符串。
        /// </summary>
        internal static string DocumentLabel {
            get {
                return ResourceManager.GetString("DocumentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档参数 的本地化字符串。
        /// </summary>
        internal static string DocumentParameter {
            get {
                return ResourceManager.GetString("DocumentParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖拽“{0}”的数据点。 的本地化字符串。
        /// </summary>
        internal static string DragValuePoint_Name {
            get {
                return ResourceManager.GetString("DragValuePoint_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖拽数据点，不修改时间。 的本地化字符串。
        /// </summary>
        internal static string DragValuePointFixedTime {
            get {
                return ResourceManager.GetString("DragValuePointFixedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改“{0}”的数据点 的本地化字符串。
        /// </summary>
        internal static string EditValuePoint_Title {
            get {
                return ResourceManager.GetString("EditValuePoint_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页脚数据行 的本地化字符串。
        /// </summary>
        internal static string FooterLine {
            get {
                return ResourceManager.GetString("FooterLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页眉标签 的本地化字符串。
        /// </summary>
        internal static string HeaderLabel {
            get {
                return ResourceManager.GetString("HeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页眉数据行 的本地化字符串。
        /// </summary>
        internal static string HeaderTitleLine {
            get {
                return ResourceManager.GetString("HeaderTitleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片文件(*.png,*.bmp,*.jpg,*.jpeg,*.gif)|*.png;*.bmp;*.jpg;*.jpeg;*.gif 的本地化字符串。
        /// </summary>
        internal static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0} 的本地化字符串。
        /// </summary>
        internal static string InputTitle_Name {
            get {
                return ResourceManager.GetString("InputTitle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0} 最小值{1}，最大值{2}。 的本地化字符串。
        /// </summary>
        internal static string InputTitle_Name_Min_Max {
            get {
                return ResourceManager.GetString("InputTitle_Name_Min_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的{0}超出范围（最小值{1}，最大值{2}）。 的本地化字符串。
        /// </summary>
        internal static string InputValueOutofRange_Title__MinValue_MaxValue {
            get {
                return ResourceManager.GetString("InputValueOutofRange_Title__MinValue_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增“{0}”的数据点 的本地化字符串。
        /// </summary>
        internal static string NewValuePoint_Name {
            get {
                return ResourceManager.GetString("NewValuePoint_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超出最大值为“{0}”最小值为“{1}”的取值范围。 的本地化字符串。
        /// </summary>
        internal static string OutofRange_Max_Min {
            get {
                return ResourceManager.GetString("OutofRange_Max_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认是否删除数据“{0}”，时间为“{1}”，数值为“{2}”？ 的本地化字符串。
        /// </summary>
        internal static string PromptDeleteValuePoint_Title_Time_Value {
            get {
                return ResourceManager.GetString("PromptDeleteValuePoint_Title_Time_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在特定时间区域，无法以分页方式显示。 的本地化字符串。
        /// </summary>
        internal static string PromptExistTimeZone {
            get {
                return ResourceManager.GetString("PromptExistTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击展开或收缩数据行。 的本地化字符串。
        /// </summary>
        internal static string PromptExpandedCollapseTitleLine {
            get {
                return ResourceManager.GetString("PromptExpandedCollapseTitleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击展开或收缩时间区域。 的本地化字符串。
        /// </summary>
        internal static string PromptExpandedCollapseZone {
            get {
                return ResourceManager.GetString("PromptExpandedCollapseZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须输入数据。 的本地化字符串。
        /// </summary>
        internal static string RequiredValue {
            get {
                return ResourceManager.GetString("RequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统提示 的本地化字符串。
        /// </summary>
        internal static string SystemAlert {
            get {
                return ResourceManager.GetString("SystemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间区域 的本地化字符串。
        /// </summary>
        internal static string TimeLineZone {
            get {
                return ResourceManager.GetString("TimeLineZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [未注册，请注册本软件] 的本地化字符串。
        /// </summary>
        internal static string UnRegisterTitle {
            get {
                return ResourceManager.GetString("UnRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值 的本地化字符串。
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间刻度太小，是否继续操作？ 的本地化字符串。
        /// </summary>
        internal static string WarringSmallTickStep {
            get {
                return ResourceManager.GetString("WarringSmallTickStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理，请稍候... 的本地化字符串。
        /// </summary>
        internal static string Watting {
            get {
                return ResourceManager.GetString("Watting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据标尺 的本地化字符串。
        /// </summary>
        internal static string YAxis {
            get {
                return ResourceManager.GetString("YAxis", resourceCulture);
            }
        }
    }
}
