# Panel 类
https://learn.microsoft.com/zh-cn/dotnet/api/system.windows.forms.panel?view=netframework-4.8
## 构造函数

| 名称 | 说明 |  |
| --- | --- | --- |
| [Panel()](system.windows.forms.panel.-ctor#system-windows-forms-panel-ctor) | 初始化 [Panel](system.windows.forms.panel) 类的新实例。 |  |

## 字段

| 名称 | 说明 |  |
| --- | --- | --- |
| [ScrollStateAutoScrolling](system.windows.forms.scrollablecontrol.scrollstateautoscrolling#system-windows-forms-scrollablecontrol-scrollstateautoscrolling) | 确定属性的值 [AutoScroll](system.windows.forms.scrollablecontrol.autoscroll#system-windows-forms-scrollablecontrol-autoscroll) 。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [ScrollStateFullDrag](system.windows.forms.scrollablecontrol.scrollstatefulldrag#system-windows-forms-scrollablecontrol-scrollstatefulldrag) | 确定用户是否已启用全屏拖动。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [ScrollStateHScrollVisible](system.windows.forms.scrollablecontrol.scrollstatehscrollvisible#system-windows-forms-scrollablecontrol-scrollstatehscrollvisible) | 确定属性的值 [HScroll](system.windows.forms.scrollablecontrol.hscroll#system-windows-forms-scrollablecontrol-hscroll) 是否设置为 `true`。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [ScrollStateUserHasScrolled](system.windows.forms.scrollablecontrol.scrollstateuserhasscrolled#system-windows-forms-scrollablecontrol-scrollstateuserhasscrolled) | 确定用户是否已滚动浏览控件 [ScrollableControl](system.windows.forms.scrollablecontrol) 。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [ScrollStateVScrollVisible](system.windows.forms.scrollablecontrol.scrollstatevscrollvisible#system-windows-forms-scrollablecontrol-scrollstatevscrollvisible) | 确定属性的值 [VScroll](system.windows.forms.scrollablecontrol.vscroll#system-windows-forms-scrollablecontrol-vscroll) 是否设置为 `true`。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |

## 属性

| 名称 | 说明 |  |
| --- | --- | --- |
| [AccessibilityObject](system.windows.forms.control.accessibilityobject#system-windows-forms-control-accessibilityobject) | [AccessibleObject](system.windows.forms.accessibleobject)获取分配给控件的控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [AccessibleDefaultActionDescription](system.windows.forms.control.accessibledefaultactiondescription#system-windows-forms-control-accessibledefaultactiondescription) | 获取或设置控件的默认操作说明，以供辅助功能客户端应用程序使用。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [AccessibleDescription](system.windows.forms.control.accessibledescription#system-windows-forms-control-accessibledescription) | 获取或设置辅助功能客户端应用程序使用的控件的说明。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [AccessibleName](system.windows.forms.control.accessiblename#system-windows-forms-control-accessiblename) | 获取或设置辅助功能客户端应用程序使用的控件的名称。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [AccessibleRole](system.windows.forms.control.accessiblerole#system-windows-forms-control-accessiblerole) | 获取或设置控件的可访问角色。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [AllowDrop](system.windows.forms.control.allowdrop#system-windows-forms-control-allowdrop) | 获取或设置一个值，该值指示控件是否可以接受用户拖动到其中的数据。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Anchor](system.windows.forms.control.anchor#system-windows-forms-control-anchor) | 获取或设置控件绑定到的容器的边缘，并确定控件的父级如何调整其大小。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [AutoScroll](system.windows.forms.scrollablecontrol.autoscroll#system-windows-forms-scrollablecontrol-autoscroll) | 获取或设置一个值，该值指示容器是否允许用户滚动到其可见边界之外的任何控件。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [AutoScrollMargin](system.windows.forms.scrollablecontrol.autoscrollmargin#system-windows-forms-scrollablecontrol-autoscrollmargin) | 获取或设置自动滚动边距的大小。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [AutoScrollMinSize](system.windows.forms.scrollablecontrol.autoscrollminsize#system-windows-forms-scrollablecontrol-autoscrollminsize) | 获取或设置自动滚动的最小大小。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [AutoScrollOffset](system.windows.forms.control.autoscrolloffset#system-windows-forms-control-autoscrolloffset) | 获取或设置此控件滚动到的位置 [ScrollControlIntoView(Control)](system.windows.forms.scrollablecontrol.scrollcontrolintoview#system-windows-forms-scrollablecontrol-scrollcontrolintoview%28system-windows-forms-control%29)。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [AutoScrollPosition](system.windows.forms.scrollablecontrol.autoscrollposition#system-windows-forms-scrollablecontrol-autoscrollposition) | 获取或设置自动滚动位置的位置。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [AutoSize](system.windows.forms.panel.autosize#system-windows-forms-panel-autosize) | 获取或设置一个值，该值指示控件是否根据其内容调整大小。 |  |
| [AutoSizeMode](system.windows.forms.panel.autosizemode#system-windows-forms-panel-autosizemode) | 指示控件的自动大小调整行为。 |  |
| [BackColor](system.windows.forms.control.backcolor#system-windows-forms-control-backcolor) | 获取或设置控件的背景色。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [BackgroundImage](system.windows.forms.control.backgroundimage#system-windows-forms-control-backgroundimage) | 获取或设置控件中显示的背景图像。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [BackgroundImageLayout](system.windows.forms.control.backgroundimagelayout#system-windows-forms-control-backgroundimagelayout) | 获取或设置枚举中 [ImageLayout](system.windows.forms.imagelayout) 定义的背景图像布局。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [BindingContext](system.windows.forms.control.bindingcontext#system-windows-forms-control-bindingcontext) | 获取或设置 [BindingContext](system.windows.forms.bindingcontext) 控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [BorderStyle](system.windows.forms.panel.borderstyle#system-windows-forms-panel-borderstyle) | 指示控件的边框样式。 |  |
| [Bottom](system.windows.forms.control.bottom#system-windows-forms-control-bottom) | 获取控件的下边缘与其容器工作区的上边缘之间的距离（以像素为单位）。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Bounds](system.windows.forms.control.bounds#system-windows-forms-control-bounds) | 获取或设置控件的大小和位置，包括其相对于父控件的非client 元素（以像素为单位）。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CanEnableIme](system.windows.forms.control.canenableime#system-windows-forms-control-canenableime) | 获取一个值，该值指示属性是否可以 [ImeMode](system.windows.forms.control.imemode#system-windows-forms-control-imemode) 设置为活动值，以启用 IME 支持。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CanFocus](system.windows.forms.control.canfocus#system-windows-forms-control-canfocus) | 获取一个值，该值指示控件是否可以接收焦点。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CanRaiseEvents](system.windows.forms.control.canraiseevents#system-windows-forms-control-canraiseevents) | 确定是否可以在控件上引发事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CanSelect](system.windows.forms.control.canselect#system-windows-forms-control-canselect) | 获取一个值，该值指示是否可以选择控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Capture](system.windows.forms.control.capture#system-windows-forms-control-capture) | 获取或设置一个值，该值指示控件是否已捕获鼠标。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CausesValidation](system.windows.forms.control.causesvalidation#system-windows-forms-control-causesvalidation) | 获取或设置一个值，该值指示控件是否导致验证在收到焦点时需要验证的任何控件上执行。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ClientRectangle](system.windows.forms.control.clientrectangle#system-windows-forms-control-clientrectangle) | 获取表示控件工作区的矩形。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ClientSize](system.windows.forms.control.clientsize#system-windows-forms-control-clientsize) | 获取或设置控件工作区的高度和宽度。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CompanyName](system.windows.forms.control.companyname#system-windows-forms-control-companyname) | 获取包含控件的应用程序的公司或创建者的名称。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Container](system.componentmodel.component.container#system-componentmodel-component-container) | [IContainer](system.componentmodel.icontainer)获取包含 .[Component](system.componentmodel.component)<br> (继承自 [Component](system.componentmodel.component)) |  |
| [ContainsFocus](system.windows.forms.control.containsfocus#system-windows-forms-control-containsfocus) | 获取一个值，该值指示控件或其子控件之一当前是否具有输入焦点。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ContextMenu](system.windows.forms.control.contextmenu#system-windows-forms-control-contextmenu) | ::: moniker range=" windowsdesktop-10.0 windowsdesktop-11.0 "<br>**已过时.**<br><br>::: moniker-end<br><br>获取或设置与控件关联的快捷菜单。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ContextMenuStrip](system.windows.forms.control.contextmenustrip#system-windows-forms-control-contextmenustrip) | 获取或设置 [ContextMenuStrip](system.windows.forms.contextmenustrip) 与此控件关联的值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Controls](system.windows.forms.control.controls#system-windows-forms-control-controls) | 获取控件中包含的控件的集合。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Created](system.windows.forms.control.created#system-windows-forms-control-created) | 获取一个值，该值指示是否已创建控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CreateParams](system.windows.forms.panel.createparams#system-windows-forms-panel-createparams) | 获取创建控件句柄时所需的创建参数。 |  |
| [Cursor](system.windows.forms.control.cursor#system-windows-forms-control-cursor) | 获取或设置鼠标指针位于控件上时显示的光标。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DataBindings](system.windows.forms.control.databindings#system-windows-forms-control-databindings) | 获取控件的数据绑定。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DataContext](system.windows.forms.control.datacontext#system-windows-forms-control-datacontext) | 获取或设置用于数据绑定的数据上下文。 这是一个环境属性。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DefaultCursor](system.windows.forms.control.defaultcursor#system-windows-forms-control-defaultcursor) | 获取或设置控件的默认游标。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DefaultImeMode](system.windows.forms.control.defaultimemode#system-windows-forms-control-defaultimemode) | 获取控件支持的默认输入法编辑器 （IME） 模式。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DefaultMargin](system.windows.forms.control.defaultmargin#system-windows-forms-control-defaultmargin) | 获取默认情况下在控件之间指定的空间（以像素为单位）。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DefaultMaximumSize](system.windows.forms.control.defaultmaximumsize#system-windows-forms-control-defaultmaximumsize) | 获取指定为控件的默认最大大小的长度和高度（以像素为单位）。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DefaultMinimumSize](system.windows.forms.control.defaultminimumsize#system-windows-forms-control-defaultminimumsize) | 获取指定为控件的默认最小大小的长度和高度（以像素为单位）。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DefaultPadding](system.windows.forms.control.defaultpadding#system-windows-forms-control-defaultpadding) | 获取控件内容的默认内部间距（以像素为单位）。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DefaultSize](system.windows.forms.panel.defaultsize#system-windows-forms-panel-defaultsize) | 获取控件的默认大小。 |  |
| [DesignMode](system.componentmodel.component.designmode#system-componentmodel-component-designmode) | 获取一个值，该值指示当前是否 [Component](system.componentmodel.component) 处于设计模式。<br> (继承自 [Component](system.componentmodel.component)) |  |
| [DeviceDpi](system.windows.forms.control.devicedpi#system-windows-forms-control-devicedpi) | 获取当前显示控件的显示设备的 DPI 值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DisplayRectangle](system.windows.forms.scrollablecontrol.displayrectangle#system-windows-forms-scrollablecontrol-displayrectangle) | 获取表示控件的虚拟显示区域的矩形。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [Disposing](system.windows.forms.control.disposing#system-windows-forms-control-disposing) | 获取一个值，该值指示基 [Control](system.windows.forms.control) 类是否正在处理。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Dock](system.windows.forms.control.dock#system-windows-forms-control-dock) | 获取或设置哪些控件边框停靠到其父控件，并确定控件如何调整其父级的大小。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DockPadding](system.windows.forms.scrollablecontrol.dockpadding#system-windows-forms-scrollablecontrol-dockpadding) | 获取控件的所有边缘的停靠填充设置。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [DoubleBuffered](system.windows.forms.control.doublebuffered#system-windows-forms-control-doublebuffered) | 获取或设置一个值，该值指示此控件是否应使用辅助缓冲区重新绘制其表面以减少或防止闪烁。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Enabled](system.windows.forms.control.enabled#system-windows-forms-control-enabled) | 获取或设置一个值，该值指示控件是否可以响应用户交互。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Events](system.componentmodel.component.events#system-componentmodel-component-events) | 获取附加到此 [Component](system.componentmodel.component)对象的事件处理程序的列表。<br> (继承自 [Component](system.componentmodel.component)) |  |
| [Focused](system.windows.forms.control.focused#system-windows-forms-control-focused) | 获取一个值，该值指示控件是否具有输入焦点。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Font](system.windows.forms.control.font#system-windows-forms-control-font) | 获取或设置控件显示的文本的字体。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [FontHeight](system.windows.forms.control.fontheight#system-windows-forms-control-fontheight) | 获取或设置控件字体的高度。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ForeColor](system.windows.forms.control.forecolor#system-windows-forms-control-forecolor) | 获取或设置控件的前景色。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Handle](system.windows.forms.control.handle#system-windows-forms-control-handle) | 获取控件绑定到的窗口句柄。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [HasChildren](system.windows.forms.control.haschildren#system-windows-forms-control-haschildren) | 获取一个值，该值指示控件是否包含一个或多个子控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Height](system.windows.forms.control.height#system-windows-forms-control-height) | 获取或设置控件的高度。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [HorizontalScroll](system.windows.forms.scrollablecontrol.horizontalscroll#system-windows-forms-scrollablecontrol-horizontalscroll) | 获取与水平滚动条关联的特征。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [HScroll](system.windows.forms.scrollablecontrol.hscroll#system-windows-forms-scrollablecontrol-hscroll) | 获取或设置一个值，该值指示水平滚动条是否可见。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [ImeMode](system.windows.forms.control.imemode#system-windows-forms-control-imemode) | 获取或设置控件的输入法编辑器 （IME） 模式。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ImeModeBase](system.windows.forms.control.imemodebase#system-windows-forms-control-imemodebase) | 获取或设置控件的 IME 模式。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [InvokeRequired](system.windows.forms.control.invokerequired#system-windows-forms-control-invokerequired) | 获取一个值，该值指示调用方在对控件进行方法调用时是否必须调用调用方法，因为调用方与创建控件的线程不同。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [IsAccessible](system.windows.forms.control.isaccessible#system-windows-forms-control-isaccessible) | 获取或设置一个值，该值指示控件是否对辅助功能应用程序可见。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [IsAncestorSiteInDesignMode](system.windows.forms.control.isancestorsiteindesignmode#system-windows-forms-control-isancestorsiteindesignmode) | 指示此控件的上级位置之一是否位于 DesignMode 中。 此属性为只读。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [IsDisposed](system.windows.forms.control.isdisposed#system-windows-forms-control-isdisposed) | 获取一个值，该值指示控件是否已释放。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [IsHandleCreated](system.windows.forms.control.ishandlecreated#system-windows-forms-control-ishandlecreated) | 获取一个值，该值指示控件是否具有与之关联的句柄。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [IsMirrored](system.windows.forms.control.ismirrored#system-windows-forms-control-ismirrored) | 获取一个值，该值指示控件是否镜像。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [LayoutEngine](system.windows.forms.control.layoutengine#system-windows-forms-control-layoutengine) | 获取控件布局引擎的缓存实例。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Left](system.windows.forms.control.left#system-windows-forms-control-left) | 获取或设置控件左边缘与其容器工作区的左边缘之间的距离（以像素为单位）。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Location](system.windows.forms.control.location#system-windows-forms-control-location) | 获取或设置控件左上角相对于其容器左上角的坐标。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Margin](system.windows.forms.control.margin#system-windows-forms-control-margin) | 获取或设置控件之间的间距。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [MaximumSize](system.windows.forms.control.maximumsize#system-windows-forms-control-maximumsize) | 获取或设置可指定上限 [GetPreferredSize(Size)](system.windows.forms.control.getpreferredsize#system-windows-forms-control-getpreferredsize%28system-drawing-size%29) 的大小。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [MinimumSize](system.windows.forms.control.minimumsize#system-windows-forms-control-minimumsize) | 获取或设置可以指定的下限 [GetPreferredSize(Size)](system.windows.forms.control.getpreferredsize#system-windows-forms-control-getpreferredsize%28system-drawing-size%29) 的大小。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Name](system.windows.forms.control.name#system-windows-forms-control-name) | 获取或设置控件的名称。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Padding](system.windows.forms.control.padding#system-windows-forms-control-padding) | 获取或设置控件中的填充。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Parent](system.windows.forms.control.parent#system-windows-forms-control-parent) | 获取或设置控件的父容器。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [PreferredSize](system.windows.forms.control.preferredsize#system-windows-forms-control-preferredsize) | 获取控件可以容纳到的矩形区域的大小。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ProductName](system.windows.forms.control.productname#system-windows-forms-control-productname) | 获取包含控件的程序集的产品名称。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ProductVersion](system.windows.forms.control.productversion#system-windows-forms-control-productversion) | 获取包含控件的程序集的版本。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RecreatingHandle](system.windows.forms.control.recreatinghandle#system-windows-forms-control-recreatinghandle) | 获取一个值，该值指示控件当前是否正在重新创建其句柄。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Region](system.windows.forms.control.region#system-windows-forms-control-region) | 获取或设置与控件关联的窗口区域。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RenderRightToLeft](system.windows.forms.control.renderrighttoleft#system-windows-forms-control-renderrighttoleft) | ::: moniker range=" netframework-2.0 netframework-3.0 netframework-3.5 netframework-4.0 netframework-4.5 netframework-4.5.1 netframework-4.5.2 netframework-4.6 netframework-4.6.1 netframework-4.6.2 netframework-4.7 netframework-4.7.1 netframework-4.7.2 netframework-4.8 netframework-4.8.1 windowsdesktop-3.0 windowsdesktop-3.1 windowsdesktop-5.0 "<br>**已过时.**<br><br>::: moniker-end<br><br>::: moniker range=" windowsdesktop-10.0 windowsdesktop-11.0 windowsdesktop-6.0 windowsdesktop-7.0 windowsdesktop-8.0 windowsdesktop-9.0 "<br>**已过时.**<br><br>::: moniker-end<br><br>此属性现已过时。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResizeRedraw](system.windows.forms.control.resizeredraw#system-windows-forms-control-resizeredraw) | 获取或设置一个值，该值指示控件在调整大小时是否重新绘制自身。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Right](system.windows.forms.control.right#system-windows-forms-control-right) | 获取控件右边缘与其容器工作区的左边缘之间的距离（以像素为单位）。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RightToLeft](system.windows.forms.control.righttoleft#system-windows-forms-control-righttoleft) | 获取或设置一个值，该值指示控件的元素是否对齐以支持使用从右到左字体的区域设置。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ScaleChildren](system.windows.forms.control.scalechildren#system-windows-forms-control-scalechildren) | 获取一个值，该值确定子控件的缩放。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ShowFocusCues](system.windows.forms.control.showfocuscues#system-windows-forms-control-showfocuscues) | 获取一个值，该值指示控件是否应显示焦点矩形。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ShowKeyboardCues](system.windows.forms.control.showkeyboardcues#system-windows-forms-control-showkeyboardcues) | 获取一个值，该值指示用户界面是否处于适当的状态以显示或隐藏键盘加速器。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Site](system.windows.forms.control.site#system-windows-forms-control-site) | 获取或设置控件的站点。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Size](system.windows.forms.control.size#system-windows-forms-control-size) | 获取或设置控件的高度和宽度。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [TabIndex](system.windows.forms.control.tabindex#system-windows-forms-control-tabindex) | 获取或设置控件在其容器中的 Tab 键顺序。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [TabStop](system.windows.forms.panel.tabstop#system-windows-forms-panel-tabstop) | 获取或设置一个值，该值指示用户是否可以使用 TAB 键向此控件提供焦点。 |  |
| [Tag](system.windows.forms.control.tag#system-windows-forms-control-tag) | 获取或设置包含有关控件的数据的对象。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Text](system.windows.forms.panel.text#system-windows-forms-panel-text) | 此成员对此控件没有意义。 |  |
| [Top](system.windows.forms.control.top#system-windows-forms-control-top) | 获取或设置控件上边缘与其容器工作区上边缘之间的距离（以像素为单位）。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [TopLevelControl](system.windows.forms.control.toplevelcontrol#system-windows-forms-control-toplevelcontrol) | 获取其他 Windows 窗体控件未父控件的父控件。 通常，这是控件包含在的最外层 [Form](system.windows.forms.form) 。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [UseWaitCursor](system.windows.forms.control.usewaitcursor#system-windows-forms-control-usewaitcursor) | 获取或设置一个值，该值指示是否对当前控件和所有子控件使用等待游标。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [VerticalScroll](system.windows.forms.scrollablecontrol.verticalscroll#system-windows-forms-scrollablecontrol-verticalscroll) | 获取与垂直滚动条关联的特征。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [Visible](system.windows.forms.control.visible#system-windows-forms-control-visible) | 获取或设置一个值，该值指示是否显示控件及其所有子控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [VScroll](system.windows.forms.scrollablecontrol.vscroll#system-windows-forms-scrollablecontrol-vscroll) | 获取或设置一个值，该值指示垂直滚动条是否可见。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [Width](system.windows.forms.control.width#system-windows-forms-control-width) | 获取或设置控件的宽度。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [WindowTarget](system.windows.forms.control.windowtarget#system-windows-forms-control-windowtarget) | 此属性与此类无关。<br> (继承自 [Control](system.windows.forms.control)) |  |

## 方法

| 名称 | 说明 |  |
| --- | --- | --- |
| [AccessibilityNotifyClients(AccessibleEvents, Int32, Int32)](system.windows.forms.control.accessibilitynotifyclients#system-windows-forms-control-accessibilitynotifyclients%28system-windows-forms-accessibleevents-system-int32-system-int32%29) | 通知为指定的子控件指定的 [AccessibleEvents](system.windows.forms.accessibleevents) 辅助功能客户端应用程序。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [AccessibilityNotifyClients(AccessibleEvents, Int32)](system.windows.forms.control.accessibilitynotifyclients#system-windows-forms-control-accessibilitynotifyclients%28system-windows-forms-accessibleevents-system-int32%29) | 通知为指定的子控件指定的 [AccessibleEvents](system.windows.forms.accessibleevents) 辅助功能客户端应用程序。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [AdjustFormScrollbars(Boolean)](system.windows.forms.scrollablecontrol.adjustformscrollbars#system-windows-forms-scrollablecontrol-adjustformscrollbars%28system-boolean%29) | 根据当前控件位置和当前选定的控件调整容器上的滚动条。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [BeginInvoke(Action)](system.windows.forms.control.begininvoke#system-windows-forms-control-begininvoke%28system-action%29) | 在创建控件的基础句柄的线程上异步执行指定的委托。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [BeginInvoke(Delegate, Object\[\])](system.windows.forms.control.begininvoke#system-windows-forms-control-begininvoke%28system-delegate-system-object%28%29%29) | 在创建控件的基础句柄的线程上，使用指定的参数异步执行指定的委托。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [BeginInvoke(Delegate)](system.windows.forms.control.begininvoke#system-windows-forms-control-begininvoke%28system-delegate%29) | 在创建控件的基础句柄的线程上异步执行指定的委托。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [BringToFront()](system.windows.forms.control.bringtofront#system-windows-forms-control-bringtofront) | 将控件置于 z 顺序的前面。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Contains(Control)](system.windows.forms.control.contains#system-windows-forms-control-contains%28system-windows-forms-control%29) | 检索一个值，该值指示指定的控件是否为控件的子级。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CreateAccessibilityInstance()](system.windows.forms.panel.createaccessibilityinstance#system-windows-forms-panel-createaccessibilityinstance) | 为此 [Panel](system.windows.forms.panel) 实例创建新的 AccessibleObject。 此方法返回的 AccessibleObject 实例支持 ControlType UIA 属性。 |  |
| [CreateAccessibilityInstance()](system.windows.forms.control.createaccessibilityinstance#system-windows-forms-control-createaccessibilityinstance) | 为控件创建新的辅助功能对象。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CreateControl()](system.windows.forms.control.createcontrol#system-windows-forms-control-createcontrol) | 强制创建可见控件，包括创建句柄和任何可见子控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CreateControlsInstance()](system.windows.forms.control.createcontrolsinstance#system-windows-forms-control-createcontrolsinstance) | 为控件创建控件集合的新实例。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CreateGraphics()](system.windows.forms.control.creategraphics#system-windows-forms-control-creategraphics) | [Graphics](system.drawing.graphics)创建控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CreateHandle()](system.windows.forms.control.createhandle#system-windows-forms-control-createhandle) | 为控件创建句柄。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [CreateObjRef(Type)](system.marshalbyrefobject.createobjref#system-marshalbyrefobject-createobjref%28system-type%29) | 创建一个对象，其中包含生成用于与远程对象通信的代理所需的所有相关信息。<br> (继承自 [MarshalByRefObject](system.marshalbyrefobject)) |  |
| [DefWndProc(Message)](system.windows.forms.control.defwndproc#system-windows-forms-control-defwndproc%28system-windows-forms-message@%29) | 将指定的消息发送到默认窗口过程。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DestroyHandle()](system.windows.forms.control.destroyhandle#system-windows-forms-control-destroyhandle) | 销毁与控件关联的句柄。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Dispose()](system.componentmodel.component.dispose#system-componentmodel-component-dispose) | 释放该 [Component](system.componentmodel.component)命令使用的所有资源。<br> (继承自 [Component](system.componentmodel.component)) |  |
| [Dispose(Boolean)](system.windows.forms.control.dispose#system-windows-forms-control-dispose%28system-boolean%29) | 释放由及其子控件使用 [Control](system.windows.forms.control) 的非托管资源，并选择性地释放托管资源。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DoDragDrop(Object, DragDropEffects, Bitmap, Point, Boolean)](system.windows.forms.control.dodragdrop#system-windows-forms-control-dodragdrop%28system-object-system-windows-forms-dragdropeffects-system-drawing-bitmap-system-drawing-point-system-boolean%29) | 开始拖动操作。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DoDragDrop(Object, DragDropEffects)](system.windows.forms.control.dodragdrop#system-windows-forms-control-dodragdrop%28system-object-system-windows-forms-dragdropeffects%29) | 开始拖放操作。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DoDragDropAsJson&lt;T&gt;(T, DragDropEffects, Bitmap, Point, Boolean)](system.windows.forms.control.dodragdropasjson#system-windows-forms-control-dodragdropasjson-1%28-0-system-windows-forms-dragdropeffects-system-drawing-bitmap-system-drawing-point-system-boolean%29) | 用于对控件集合进行分组。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DoDragDropAsJson&lt;T&gt;(T, DragDropEffects)](system.windows.forms.control.dodragdropasjson#system-windows-forms-control-dodragdropasjson-1%28-0-system-windows-forms-dragdropeffects%29) | 用于对控件集合进行分组。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [DrawToBitmap(Bitmap, Rectangle)](system.windows.forms.control.drawtobitmap#system-windows-forms-control-drawtobitmap%28system-drawing-bitmap-system-drawing-rectangle%29) | 支持呈现到指定的位图。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [EndInvoke(IAsyncResult)](system.windows.forms.control.endinvoke#system-windows-forms-control-endinvoke%28system-iasyncresult%29) | 检索传递的异步操作 [IAsyncResult](system.iasyncresult) 的返回值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Equals(Object)](system.object.equals#system-object-equals%28system-object%29) | 确定指定的对象是否等于当前对象。<br> (继承自 [Object](system.object)) |  |
| [FindForm()](system.windows.forms.control.findform#system-windows-forms-control-findform) | 检索控件打开的窗体。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Focus()](system.windows.forms.control.focus#system-windows-forms-control-focus) | 将输入焦点设置为控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [GetAccessibilityObjectById(Int32)](system.windows.forms.control.getaccessibilityobjectbyid#system-windows-forms-control-getaccessibilityobjectbyid%28system-int32%29) | 检索指定的 [AccessibleObject](system.windows.forms.accessibleobject)。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [GetAutoSizeMode()](system.windows.forms.control.getautosizemode#system-windows-forms-control-getautosizemode) | 检索一个值，该值指示控件在启用控件 [AutoSize](system.windows.forms.control.autosize#system-windows-forms-control-autosize) 属性时的行为方式。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [GetChildAtPoint(Point, GetChildAtPointSkip)](system.windows.forms.control.getchildatpoint#system-windows-forms-control-getchildatpoint%28system-drawing-point-system-windows-forms-getchildatpointskip%29) | 检索位于指定坐标处的子控件，指定是否忽略特定类型的子控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [GetChildAtPoint(Point)](system.windows.forms.control.getchildatpoint#system-windows-forms-control-getchildatpoint%28system-drawing-point%29) | 检索位于指定坐标处的子控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [GetContainerControl()](system.windows.forms.control.getcontainercontrol#system-windows-forms-control-getcontainercontrol) | 返回控件的父控件链的下一个 [ContainerControl](system.windows.forms.containercontrol) 。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [GetHashCode()](system.object.gethashcode#system-object-gethashcode) | 用作默认哈希函数。<br> (继承自 [Object](system.object)) |  |
| [GetLifetimeService()](system.marshalbyrefobject.getlifetimeservice#system-marshalbyrefobject-getlifetimeservice) | ::: moniker range=" net-10.0 net-11.0 net-5.0 net-6.0 net-7.0 net-8.0 net-9.0 "<br>**已过时.**<br><br>::: moniker-end<br><br>检索控制此实例的生存期策略的当前生存期服务对象。<br> (继承自 [MarshalByRefObject](system.marshalbyrefobject)) |  |
| [GetNextControl(Control, Boolean)](system.windows.forms.control.getnextcontrol#system-windows-forms-control-getnextcontrol%28system-windows-forms-control-system-boolean%29) | 按子控件的 Tab 键顺序检索下一个控件向前或后退。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [GetPreferredSize(Size)](system.windows.forms.control.getpreferredsize#system-windows-forms-control-getpreferredsize%28system-drawing-size%29) | 检索可安装控件的矩形区域的大小。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [GetScaledBounds(Rectangle, SizeF, BoundsSpecified)](system.windows.forms.control.getscaledbounds#system-windows-forms-control-getscaledbounds%28system-drawing-rectangle-system-drawing-sizef-system-windows-forms-boundsspecified%29) | 检索在其中缩放控件的边界。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [GetScrollState(Int32)](system.windows.forms.scrollablecontrol.getscrollstate#system-windows-forms-scrollablecontrol-getscrollstate%28system-int32%29) | 确定是否已设置指定的标志。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [GetService(Type)](system.componentmodel.component.getservice#system-componentmodel-component-getservice%28system-type%29) | 返回一个对象，该对象表示服务由 [Component](system.componentmodel.component) 或其 [Container](system.componentmodel.container)提供的服务。<br> (继承自 [Component](system.componentmodel.component)) |  |
| [GetStyle(ControlStyles)](system.windows.forms.control.getstyle#system-windows-forms-control-getstyle%28system-windows-forms-controlstyles%29) | 检索控件的指定控件样式位的值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [GetTopLevel()](system.windows.forms.control.gettoplevel#system-windows-forms-control-gettoplevel) | 确定控件是否为顶级控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [GetType()](system.object.gettype#system-object-gettype) | 获取当前实例的 [Type](system.type)。<br> (继承自 [Object](system.object)) |  |
| [Hide()](system.windows.forms.control.hide#system-windows-forms-control-hide) | 隐藏用户的控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [InitializeLifetimeService()](system.marshalbyrefobject.initializelifetimeservice#system-marshalbyrefobject-initializelifetimeservice) | ::: moniker range=" net-10.0 net-11.0 net-5.0 net-6.0 net-7.0 net-8.0 net-9.0 "<br>**已过时.**<br><br>::: moniker-end<br><br>获取生存期服务对象来控制此实例的生存期策略。<br> (继承自 [MarshalByRefObject](system.marshalbyrefobject)) |  |
| [InitLayout()](system.windows.forms.control.initlayout#system-windows-forms-control-initlayout) | 在控件添加到另一个容器后调用。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Invalidate()](system.windows.forms.control.invalidate#system-windows-forms-control-invalidate) | 使控件的整个图面失效，并使控件重新绘制。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Invalidate(Boolean)](system.windows.forms.control.invalidate#system-windows-forms-control-invalidate%28system-boolean%29) | 使控件的特定区域失效，并导致绘制消息发送到控件。 （可选）使分配给控件的子控件失效。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Invalidate(Rectangle, Boolean)](system.windows.forms.control.invalidate#system-windows-forms-control-invalidate%28system-drawing-rectangle-system-boolean%29) | 使控件的指定区域失效（将其添加到控件的更新区域，即将在下一次绘制操作时重新绘制的区域），并导致绘制消息发送到控件。 （可选）使分配给控件的子控件失效。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Invalidate(Rectangle)](system.windows.forms.control.invalidate#system-windows-forms-control-invalidate%28system-drawing-rectangle%29) | 使控件的指定区域失效（将其添加到控件的更新区域，即将在下一次绘制操作时重新绘制的区域），并导致绘制消息发送到控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Invalidate(Region, Boolean)](system.windows.forms.control.invalidate#system-windows-forms-control-invalidate%28system-drawing-region-system-boolean%29) | 使控件的指定区域失效（将其添加到控件的更新区域，即将在下一次绘制操作时重新绘制的区域），并导致绘制消息发送到控件。 （可选）使分配给控件的子控件失效。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Invalidate(Region)](system.windows.forms.control.invalidate#system-windows-forms-control-invalidate%28system-drawing-region%29) | 使控件的指定区域失效（将其添加到控件的更新区域，即将在下一次绘制操作时重新绘制的区域），并导致绘制消息发送到控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Invoke(Action)](system.windows.forms.control.invoke#system-windows-forms-control-invoke%28system-action%29) | 在拥有控件的基础窗口句柄的线程上执行指定的委托。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Invoke(Delegate, Object\[\])](system.windows.forms.control.invoke#system-windows-forms-control-invoke%28system-delegate-system-object%28%29%29) | 在拥有控件的基础窗口句柄的线程上，使用指定的参数列表执行指定的委托。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Invoke(Delegate)](system.windows.forms.control.invoke#system-windows-forms-control-invoke%28system-delegate%29) | 在拥有控件的基础窗口句柄的线程上执行指定的委托。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Invoke&lt;T&gt;(Func&lt;T&gt;)](system.windows.forms.control.invoke#system-windows-forms-control-invoke-1%28system-func%28%28-0%29%29%29) | 在拥有控件的基础窗口句柄的线程上执行指定的委托。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [InvokeAsync(Action, CancellationToken)](system.windows.forms.control.invokeasync#system-windows-forms-control-invokeasync%28system-action-system-threading-cancellationtoken%29) | 在拥有控件句柄的线程上异步调用指定的同步回调。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [InvokeAsync(Func&lt;CancellationToken,ValueTask&gt;, CancellationToken)](system.windows.forms.control.invokeasync#system-windows-forms-control-invokeasync%28system-func%28%28system-threading-cancellationtoken-system-threading-tasks-valuetask%29%29-system-threading-cancellationtoken%29) | 在拥有控件句柄的线程上执行指定的异步回调。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [InvokeAsync&lt;T&gt;(Func&lt;CancellationToken,ValueTask&lt;T&gt;&gt;, CancellationToken)](system.windows.forms.control.invokeasync#system-windows-forms-control-invokeasync-1%28system-func%28%28system-threading-cancellationtoken-system-threading-tasks-valuetask%28%28-0%29%29%29%29-system-threading-cancellationtoken%29) | 在拥有控件句柄的线程上执行指定的异步回调。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [InvokeAsync&lt;T&gt;(Func&lt;T&gt;, CancellationToken)](system.windows.forms.control.invokeasync#system-windows-forms-control-invokeasync-1%28system-func%28%28-0%29%29-system-threading-cancellationtoken%29) | 在拥有控件句柄的线程上异步调用指定的同步回调。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [InvokeGotFocus(Control, EventArgs)](system.windows.forms.control.invokegotfocus#system-windows-forms-control-invokegotfocus%28system-windows-forms-control-system-eventargs%29) | [GotFocus](system.windows.forms.control.gotfocus#system-windows-forms-control-gotfocus)引发指定控件的事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [InvokeLostFocus(Control, EventArgs)](system.windows.forms.control.invokelostfocus#system-windows-forms-control-invokelostfocus%28system-windows-forms-control-system-eventargs%29) | [LostFocus](system.windows.forms.control.lostfocus#system-windows-forms-control-lostfocus)引发指定控件的事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [InvokeOnClick(Control, EventArgs)](system.windows.forms.control.invokeonclick#system-windows-forms-control-invokeonclick%28system-windows-forms-control-system-eventargs%29) | [Click](system.windows.forms.control.click#system-windows-forms-control-click)引发指定控件的事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [InvokePaint(Control, PaintEventArgs)](system.windows.forms.control.invokepaint#system-windows-forms-control-invokepaint%28system-windows-forms-control-system-windows-forms-painteventargs%29) | [Paint](system.windows.forms.control.paint#system-windows-forms-control-paint)引发指定控件的事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [InvokePaintBackground(Control, PaintEventArgs)](system.windows.forms.control.invokepaintbackground#system-windows-forms-control-invokepaintbackground%28system-windows-forms-control-system-windows-forms-painteventargs%29) | `PaintBackground`引发指定控件的事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [IsInputChar(Char)](system.windows.forms.control.isinputchar#system-windows-forms-control-isinputchar%28system-char%29) | 确定字符是否是控件识别的输入字符。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [IsInputKey(Keys)](system.windows.forms.control.isinputkey#system-windows-forms-control-isinputkey%28system-windows-forms-keys%29) | 确定指定的键是常规输入键还是需要预处理的特殊键。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [LogicalToDeviceUnits(Int32)](system.windows.forms.control.logicaltodeviceunits#system-windows-forms-control-logicaltodeviceunits%28system-int32%29) | 将逻辑 DPI 值转换为其等效的 DeviceUnit DPI 值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [LogicalToDeviceUnits(Size)](system.windows.forms.control.logicaltodeviceunits#system-windows-forms-control-logicaltodeviceunits%28system-drawing-size%29) | 通过缩放当前 DPI 的大小并将其舍入为最接近的整数值（宽度和高度）从逻辑单位转换为设备单位。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [MemberwiseClone()](system.object.memberwiseclone#system-object-memberwiseclone) | 创建当前 [Object](system.object)的浅表副本。<br> (继承自 [Object](system.object)) |  |
| [MemberwiseClone(Boolean)](system.marshalbyrefobject.memberwiseclone#system-marshalbyrefobject-memberwiseclone%28system-boolean%29) | 创建当前 [MarshalByRefObject](system.marshalbyrefobject) 对象的浅表副本。<br> (继承自 [MarshalByRefObject](system.marshalbyrefobject)) |  |
| [NotifyInvalidate(Rectangle)](system.windows.forms.control.notifyinvalidate#system-windows-forms-control-notifyinvalidate%28system-drawing-rectangle%29) | [Invalidated](system.windows.forms.control.invalidated#system-windows-forms-control-invalidated)使用控件的指定区域引发事件，使该事件失效。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnAutoSizeChanged(EventArgs)](system.windows.forms.control.onautosizechanged#system-windows-forms-control-onautosizechanged%28system-eventargs%29) | 引发 [AutoSizeChanged](system.windows.forms.control.autosizechanged#system-windows-forms-control-autosizechanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnBackColorChanged(EventArgs)](system.windows.forms.control.onbackcolorchanged#system-windows-forms-control-onbackcolorchanged%28system-eventargs%29) | 引发 [BackColorChanged](system.windows.forms.control.backcolorchanged#system-windows-forms-control-backcolorchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnBackgroundImageChanged(EventArgs)](system.windows.forms.control.onbackgroundimagechanged#system-windows-forms-control-onbackgroundimagechanged%28system-eventargs%29) | 引发 [BackgroundImageChanged](system.windows.forms.control.backgroundimagechanged#system-windows-forms-control-backgroundimagechanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnBackgroundImageLayoutChanged(EventArgs)](system.windows.forms.control.onbackgroundimagelayoutchanged#system-windows-forms-control-onbackgroundimagelayoutchanged%28system-eventargs%29) | 引发 [BackgroundImageLayoutChanged](system.windows.forms.control.backgroundimagelayoutchanged#system-windows-forms-control-backgroundimagelayoutchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnBindingContextChanged(EventArgs)](system.windows.forms.control.onbindingcontextchanged#system-windows-forms-control-onbindingcontextchanged%28system-eventargs%29) | 引发 [BindingContextChanged](system.windows.forms.control.bindingcontextchanged#system-windows-forms-control-bindingcontextchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnCausesValidationChanged(EventArgs)](system.windows.forms.control.oncausesvalidationchanged#system-windows-forms-control-oncausesvalidationchanged%28system-eventargs%29) | 引发 [CausesValidationChanged](system.windows.forms.control.causesvalidationchanged#system-windows-forms-control-causesvalidationchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnChangeUICues(UICuesEventArgs)](system.windows.forms.control.onchangeuicues#system-windows-forms-control-onchangeuicues%28system-windows-forms-uicueseventargs%29) | 引发 [ChangeUICues](system.windows.forms.control.changeuicues#system-windows-forms-control-changeuicues) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnClick(EventArgs)](system.windows.forms.control.onclick#system-windows-forms-control-onclick%28system-eventargs%29) | 引发 [Click](system.windows.forms.control.click#system-windows-forms-control-click) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnClientSizeChanged(EventArgs)](system.windows.forms.control.onclientsizechanged#system-windows-forms-control-onclientsizechanged%28system-eventargs%29) | 引发 [ClientSizeChanged](system.windows.forms.control.clientsizechanged#system-windows-forms-control-clientsizechanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnContextMenuChanged(EventArgs)](system.windows.forms.control.oncontextmenuchanged#system-windows-forms-control-oncontextmenuchanged%28system-eventargs%29) | ::: moniker range=" windowsdesktop-10.0 windowsdesktop-11.0 "<br>**已过时.**<br><br>::: moniker-end<br><br>引发 [ContextMenuChanged](system.windows.forms.control.contextmenuchanged#system-windows-forms-control-contextmenuchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnContextMenuStripChanged(EventArgs)](system.windows.forms.control.oncontextmenustripchanged#system-windows-forms-control-oncontextmenustripchanged%28system-eventargs%29) | 引发 [ContextMenuStripChanged](system.windows.forms.control.contextmenustripchanged#system-windows-forms-control-contextmenustripchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnControlAdded(ControlEventArgs)](system.windows.forms.control.oncontroladded#system-windows-forms-control-oncontroladded%28system-windows-forms-controleventargs%29) | 引发 [ControlAdded](system.windows.forms.control.controladded#system-windows-forms-control-controladded) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnControlRemoved(ControlEventArgs)](system.windows.forms.control.oncontrolremoved#system-windows-forms-control-oncontrolremoved%28system-windows-forms-controleventargs%29) | 引发 [ControlRemoved](system.windows.forms.control.controlremoved#system-windows-forms-control-controlremoved) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnCreateControl()](system.windows.forms.control.oncreatecontrol#system-windows-forms-control-oncreatecontrol) | [CreateControl()](system.windows.forms.control.createcontrol#system-windows-forms-control-createcontrol)引发方法。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnCursorChanged(EventArgs)](system.windows.forms.control.oncursorchanged#system-windows-forms-control-oncursorchanged%28system-eventargs%29) | 引发 [CursorChanged](system.windows.forms.control.cursorchanged#system-windows-forms-control-cursorchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnDataContextChanged(EventArgs)](system.windows.forms.control.ondatacontextchanged#system-windows-forms-control-ondatacontextchanged%28system-eventargs%29) | 用于对控件集合进行分组。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnDockChanged(EventArgs)](system.windows.forms.control.ondockchanged#system-windows-forms-control-ondockchanged%28system-eventargs%29) | 引发 [DockChanged](system.windows.forms.control.dockchanged#system-windows-forms-control-dockchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnDoubleClick(EventArgs)](system.windows.forms.control.ondoubleclick#system-windows-forms-control-ondoubleclick%28system-eventargs%29) | 引发 [DoubleClick](system.windows.forms.control.doubleclick#system-windows-forms-control-doubleclick) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnDpiChangedAfterParent(EventArgs)](system.windows.forms.control.ondpichangedafterparent#system-windows-forms-control-ondpichangedafterparent%28system-eventargs%29) | 引发 [DpiChangedAfterParent](system.windows.forms.control.dpichangedafterparent#system-windows-forms-control-dpichangedafterparent) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnDpiChangedBeforeParent(EventArgs)](system.windows.forms.control.ondpichangedbeforeparent#system-windows-forms-control-ondpichangedbeforeparent%28system-eventargs%29) | 引发 [DpiChangedBeforeParent](system.windows.forms.control.dpichangedbeforeparent#system-windows-forms-control-dpichangedbeforeparent) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnDragDrop(DragEventArgs)](system.windows.forms.control.ondragdrop#system-windows-forms-control-ondragdrop%28system-windows-forms-drageventargs%29) | 引发 [DragDrop](system.windows.forms.control.dragdrop#system-windows-forms-control-dragdrop) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnDragEnter(DragEventArgs)](system.windows.forms.control.ondragenter#system-windows-forms-control-ondragenter%28system-windows-forms-drageventargs%29) | 引发 [DragEnter](system.windows.forms.control.dragenter#system-windows-forms-control-dragenter) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnDragLeave(EventArgs)](system.windows.forms.control.ondragleave#system-windows-forms-control-ondragleave%28system-eventargs%29) | 引发 [DragLeave](system.windows.forms.control.dragleave#system-windows-forms-control-dragleave) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnDragOver(DragEventArgs)](system.windows.forms.control.ondragover#system-windows-forms-control-ondragover%28system-windows-forms-drageventargs%29) | 引发 [DragOver](system.windows.forms.control.dragover#system-windows-forms-control-dragover) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnEnabledChanged(EventArgs)](system.windows.forms.control.onenabledchanged#system-windows-forms-control-onenabledchanged%28system-eventargs%29) | 引发 [EnabledChanged](system.windows.forms.control.enabledchanged#system-windows-forms-control-enabledchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnEnter(EventArgs)](system.windows.forms.control.onenter#system-windows-forms-control-onenter%28system-eventargs%29) | 引发 [Enter](system.windows.forms.control.enter#system-windows-forms-control-enter) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnFontChanged(EventArgs)](system.windows.forms.control.onfontchanged#system-windows-forms-control-onfontchanged%28system-eventargs%29) | 引发 [FontChanged](system.windows.forms.control.fontchanged#system-windows-forms-control-fontchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnForeColorChanged(EventArgs)](system.windows.forms.control.onforecolorchanged#system-windows-forms-control-onforecolorchanged%28system-eventargs%29) | 引发 [ForeColorChanged](system.windows.forms.control.forecolorchanged#system-windows-forms-control-forecolorchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnGiveFeedback(GiveFeedbackEventArgs)](system.windows.forms.control.ongivefeedback#system-windows-forms-control-ongivefeedback%28system-windows-forms-givefeedbackeventargs%29) | 引发 [GiveFeedback](system.windows.forms.control.givefeedback#system-windows-forms-control-givefeedback) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnGotFocus(EventArgs)](system.windows.forms.control.ongotfocus#system-windows-forms-control-ongotfocus%28system-eventargs%29) | 引发 [GotFocus](system.windows.forms.control.gotfocus#system-windows-forms-control-gotfocus) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnHandleCreated(EventArgs)](system.windows.forms.control.onhandlecreated#system-windows-forms-control-onhandlecreated%28system-eventargs%29) | 引发 [HandleCreated](system.windows.forms.control.handlecreated#system-windows-forms-control-handlecreated) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnHandleDestroyed(EventArgs)](system.windows.forms.control.onhandledestroyed#system-windows-forms-control-onhandledestroyed%28system-eventargs%29) | 引发 [HandleDestroyed](system.windows.forms.control.handledestroyed#system-windows-forms-control-handledestroyed) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnHelpRequested(HelpEventArgs)](system.windows.forms.control.onhelprequested#system-windows-forms-control-onhelprequested%28system-windows-forms-helpeventargs%29) | 引发 [HelpRequested](system.windows.forms.control.helprequested#system-windows-forms-control-helprequested) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnImeModeChanged(EventArgs)](system.windows.forms.control.onimemodechanged#system-windows-forms-control-onimemodechanged%28system-eventargs%29) | 引发 [ImeModeChanged](system.windows.forms.control.imemodechanged#system-windows-forms-control-imemodechanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnInvalidated(InvalidateEventArgs)](system.windows.forms.control.oninvalidated#system-windows-forms-control-oninvalidated%28system-windows-forms-invalidateeventargs%29) | 引发 [Invalidated](system.windows.forms.control.invalidated#system-windows-forms-control-invalidated) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnKeyDown(KeyEventArgs)](system.windows.forms.control.onkeydown#system-windows-forms-control-onkeydown%28system-windows-forms-keyeventargs%29) | 引发 [KeyDown](system.windows.forms.control.keydown#system-windows-forms-control-keydown) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnKeyPress(KeyPressEventArgs)](system.windows.forms.control.onkeypress#system-windows-forms-control-onkeypress%28system-windows-forms-keypresseventargs%29) | 引发 [KeyPress](system.windows.forms.control.keypress#system-windows-forms-control-keypress) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnKeyUp(KeyEventArgs)](system.windows.forms.control.onkeyup#system-windows-forms-control-onkeyup%28system-windows-forms-keyeventargs%29) | 引发 [KeyUp](system.windows.forms.control.keyup#system-windows-forms-control-keyup) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnLayout(LayoutEventArgs)](system.windows.forms.scrollablecontrol.onlayout#system-windows-forms-scrollablecontrol-onlayout%28system-windows-forms-layouteventargs%29) | 引发 [Layout](system.windows.forms.control.layout#system-windows-forms-control-layout) 事件。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [OnLeave(EventArgs)](system.windows.forms.control.onleave#system-windows-forms-control-onleave%28system-eventargs%29) | 引发 [Leave](system.windows.forms.control.leave#system-windows-forms-control-leave) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnLocationChanged(EventArgs)](system.windows.forms.control.onlocationchanged#system-windows-forms-control-onlocationchanged%28system-eventargs%29) | 引发 [LocationChanged](system.windows.forms.control.locationchanged#system-windows-forms-control-locationchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnLostFocus(EventArgs)](system.windows.forms.control.onlostfocus#system-windows-forms-control-onlostfocus%28system-eventargs%29) | 引发 [LostFocus](system.windows.forms.control.lostfocus#system-windows-forms-control-lostfocus) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnMarginChanged(EventArgs)](system.windows.forms.control.onmarginchanged#system-windows-forms-control-onmarginchanged%28system-eventargs%29) | 引发 [MarginChanged](system.windows.forms.control.marginchanged#system-windows-forms-control-marginchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnMouseCaptureChanged(EventArgs)](system.windows.forms.control.onmousecapturechanged#system-windows-forms-control-onmousecapturechanged%28system-eventargs%29) | 引发 [MouseCaptureChanged](system.windows.forms.control.mousecapturechanged#system-windows-forms-control-mousecapturechanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnMouseClick(MouseEventArgs)](system.windows.forms.control.onmouseclick#system-windows-forms-control-onmouseclick%28system-windows-forms-mouseeventargs%29) | 引发 [MouseClick](system.windows.forms.control.mouseclick#system-windows-forms-control-mouseclick) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnMouseDoubleClick(MouseEventArgs)](system.windows.forms.control.onmousedoubleclick#system-windows-forms-control-onmousedoubleclick%28system-windows-forms-mouseeventargs%29) | 引发 [MouseDoubleClick](system.windows.forms.control.mousedoubleclick#system-windows-forms-control-mousedoubleclick) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnMouseDown(MouseEventArgs)](system.windows.forms.control.onmousedown#system-windows-forms-control-onmousedown%28system-windows-forms-mouseeventargs%29) | 引发 [MouseDown](system.windows.forms.control.mousedown#system-windows-forms-control-mousedown) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnMouseEnter(EventArgs)](system.windows.forms.control.onmouseenter#system-windows-forms-control-onmouseenter%28system-eventargs%29) | 引发 [MouseEnter](system.windows.forms.control.mouseenter#system-windows-forms-control-mouseenter) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnMouseHover(EventArgs)](system.windows.forms.control.onmousehover#system-windows-forms-control-onmousehover%28system-eventargs%29) | 引发 [MouseHover](system.windows.forms.control.mousehover#system-windows-forms-control-mousehover) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnMouseLeave(EventArgs)](system.windows.forms.control.onmouseleave#system-windows-forms-control-onmouseleave%28system-eventargs%29) | 引发 [MouseLeave](system.windows.forms.control.mouseleave#system-windows-forms-control-mouseleave) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnMouseMove(MouseEventArgs)](system.windows.forms.control.onmousemove#system-windows-forms-control-onmousemove%28system-windows-forms-mouseeventargs%29) | 引发 [MouseMove](system.windows.forms.control.mousemove#system-windows-forms-control-mousemove) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnMouseUp(MouseEventArgs)](system.windows.forms.control.onmouseup#system-windows-forms-control-onmouseup%28system-windows-forms-mouseeventargs%29) | 引发 [MouseUp](system.windows.forms.control.mouseup#system-windows-forms-control-mouseup) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnMouseWheel(MouseEventArgs)](system.windows.forms.scrollablecontrol.onmousewheel#system-windows-forms-scrollablecontrol-onmousewheel%28system-windows-forms-mouseeventargs%29) | 引发 [MouseWheel](system.windows.forms.control.mousewheel#system-windows-forms-control-mousewheel) 事件。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [OnMove(EventArgs)](system.windows.forms.control.onmove#system-windows-forms-control-onmove%28system-eventargs%29) | 引发 [Move](system.windows.forms.control.move#system-windows-forms-control-move) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnNotifyMessage(Message)](system.windows.forms.control.onnotifymessage#system-windows-forms-control-onnotifymessage%28system-windows-forms-message%29) | 通知 Windows 消息的控制。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnPaddingChanged(EventArgs)](system.windows.forms.scrollablecontrol.onpaddingchanged#system-windows-forms-scrollablecontrol-onpaddingchanged%28system-eventargs%29) | 引发 [PaddingChanged](system.windows.forms.control.paddingchanged#system-windows-forms-control-paddingchanged) 事件。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [OnPaint(PaintEventArgs)](system.windows.forms.control.onpaint#system-windows-forms-control-onpaint%28system-windows-forms-painteventargs%29) | 引发 [Paint](system.windows.forms.control.paint#system-windows-forms-control-paint) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnPaintBackground(PaintEventArgs)](system.windows.forms.scrollablecontrol.onpaintbackground#system-windows-forms-scrollablecontrol-onpaintbackground%28system-windows-forms-painteventargs%29) | 绘制控件的背景。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [OnParentBackColorChanged(EventArgs)](system.windows.forms.control.onparentbackcolorchanged#system-windows-forms-control-onparentbackcolorchanged%28system-eventargs%29) | [BackColorChanged](system.windows.forms.control.backcolorchanged#system-windows-forms-control-backcolorchanged)当控件容器的属性值更改时[BackColor](system.windows.forms.control.backcolor#system-windows-forms-control-backcolor)引发事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnParentBackgroundImageChanged(EventArgs)](system.windows.forms.control.onparentbackgroundimagechanged#system-windows-forms-control-onparentbackgroundimagechanged%28system-eventargs%29) | [BackgroundImageChanged](system.windows.forms.control.backgroundimagechanged#system-windows-forms-control-backgroundimagechanged)当控件容器的属性值更改时[BackgroundImage](system.windows.forms.control.backgroundimage#system-windows-forms-control-backgroundimage)引发事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnParentBindingContextChanged(EventArgs)](system.windows.forms.control.onparentbindingcontextchanged#system-windows-forms-control-onparentbindingcontextchanged%28system-eventargs%29) | [BindingContextChanged](system.windows.forms.control.bindingcontextchanged#system-windows-forms-control-bindingcontextchanged)当控件容器的属性值更改时[BindingContext](system.windows.forms.control.bindingcontext#system-windows-forms-control-bindingcontext)引发事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnParentChanged(EventArgs)](system.windows.forms.control.onparentchanged#system-windows-forms-control-onparentchanged%28system-eventargs%29) | 引发 [ParentChanged](system.windows.forms.control.parentchanged#system-windows-forms-control-parentchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnParentCursorChanged(EventArgs)](system.windows.forms.control.onparentcursorchanged#system-windows-forms-control-onparentcursorchanged%28system-eventargs%29) | 引发 [CursorChanged](system.windows.forms.control.cursorchanged#system-windows-forms-control-cursorchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnParentDataContextChanged(EventArgs)](system.windows.forms.control.onparentdatacontextchanged#system-windows-forms-control-onparentdatacontextchanged%28system-eventargs%29) | 用于对控件集合进行分组。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnParentEnabledChanged(EventArgs)](system.windows.forms.control.onparentenabledchanged#system-windows-forms-control-onparentenabledchanged%28system-eventargs%29) | [EnabledChanged](system.windows.forms.control.enabledchanged#system-windows-forms-control-enabledchanged)当控件容器的属性值更改时[Enabled](system.windows.forms.control.enabled#system-windows-forms-control-enabled)引发事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnParentFontChanged(EventArgs)](system.windows.forms.control.onparentfontchanged#system-windows-forms-control-onparentfontchanged%28system-eventargs%29) | [FontChanged](system.windows.forms.control.fontchanged#system-windows-forms-control-fontchanged)当控件容器的属性值更改时[Font](system.windows.forms.control.font#system-windows-forms-control-font)引发事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnParentForeColorChanged(EventArgs)](system.windows.forms.control.onparentforecolorchanged#system-windows-forms-control-onparentforecolorchanged%28system-eventargs%29) | [ForeColorChanged](system.windows.forms.control.forecolorchanged#system-windows-forms-control-forecolorchanged)当控件容器的属性值更改时[ForeColor](system.windows.forms.control.forecolor#system-windows-forms-control-forecolor)引发事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnParentRightToLeftChanged(EventArgs)](system.windows.forms.control.onparentrighttoleftchanged#system-windows-forms-control-onparentrighttoleftchanged%28system-eventargs%29) | [RightToLeftChanged](system.windows.forms.control.righttoleftchanged#system-windows-forms-control-righttoleftchanged)当控件容器的属性值更改时[RightToLeft](system.windows.forms.control.righttoleft#system-windows-forms-control-righttoleft)引发事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnParentVisibleChanged(EventArgs)](system.windows.forms.control.onparentvisiblechanged#system-windows-forms-control-onparentvisiblechanged%28system-eventargs%29) | [VisibleChanged](system.windows.forms.control.visiblechanged#system-windows-forms-control-visiblechanged)当控件容器的属性值更改时[Visible](system.windows.forms.control.visible#system-windows-forms-control-visible)引发事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnPreviewKeyDown(PreviewKeyDownEventArgs)](system.windows.forms.control.onpreviewkeydown#system-windows-forms-control-onpreviewkeydown%28system-windows-forms-previewkeydowneventargs%29) | 引发 [PreviewKeyDown](system.windows.forms.control.previewkeydown#system-windows-forms-control-previewkeydown) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnPrint(PaintEventArgs)](system.windows.forms.control.onprint#system-windows-forms-control-onprint%28system-windows-forms-painteventargs%29) | 引发 [Paint](system.windows.forms.control.paint#system-windows-forms-control-paint) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnQueryContinueDrag(QueryContinueDragEventArgs)](system.windows.forms.control.onquerycontinuedrag#system-windows-forms-control-onquerycontinuedrag%28system-windows-forms-querycontinuedrageventargs%29) | 引发 [QueryContinueDrag](system.windows.forms.control.querycontinuedrag#system-windows-forms-control-querycontinuedrag) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnRegionChanged(EventArgs)](system.windows.forms.control.onregionchanged#system-windows-forms-control-onregionchanged%28system-eventargs%29) | 引发 [RegionChanged](system.windows.forms.control.regionchanged#system-windows-forms-control-regionchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnResize(EventArgs)](system.windows.forms.panel.onresize#system-windows-forms-panel-onresize%28system-eventargs%29) | 触发指示面板已调整大小的事件。 继承控件应使用此控件来支持实际侦听事件，但仍应调用 `base.onResize` 以确保为外部侦听器触发该事件。 |  |
| [OnRightToLeftChanged(EventArgs)](system.windows.forms.scrollablecontrol.onrighttoleftchanged#system-windows-forms-scrollablecontrol-onrighttoleftchanged%28system-eventargs%29) | 引发 [RightToLeftChanged](system.windows.forms.control.righttoleftchanged#system-windows-forms-control-righttoleftchanged) 事件。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [OnScroll(ScrollEventArgs)](system.windows.forms.scrollablecontrol.onscroll#system-windows-forms-scrollablecontrol-onscroll%28system-windows-forms-scrolleventargs%29) | 引发 [Scroll](system.windows.forms.scrollablecontrol.scroll#system-windows-forms-scrollablecontrol-scroll) 事件。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [OnSizeChanged(EventArgs)](system.windows.forms.control.onsizechanged#system-windows-forms-control-onsizechanged%28system-eventargs%29) | 引发 [SizeChanged](system.windows.forms.control.sizechanged#system-windows-forms-control-sizechanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnStyleChanged(EventArgs)](system.windows.forms.control.onstylechanged#system-windows-forms-control-onstylechanged%28system-eventargs%29) | 引发 [StyleChanged](system.windows.forms.control.stylechanged#system-windows-forms-control-stylechanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnSystemColorsChanged(EventArgs)](system.windows.forms.control.onsystemcolorschanged#system-windows-forms-control-onsystemcolorschanged%28system-eventargs%29) | 引发 [SystemColorsChanged](system.windows.forms.control.systemcolorschanged#system-windows-forms-control-systemcolorschanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnTabIndexChanged(EventArgs)](system.windows.forms.control.ontabindexchanged#system-windows-forms-control-ontabindexchanged%28system-eventargs%29) | 引发 [TabIndexChanged](system.windows.forms.control.tabindexchanged#system-windows-forms-control-tabindexchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnTabStopChanged(EventArgs)](system.windows.forms.control.ontabstopchanged#system-windows-forms-control-ontabstopchanged%28system-eventargs%29) | 引发 [TabStopChanged](system.windows.forms.control.tabstopchanged#system-windows-forms-control-tabstopchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnTextChanged(EventArgs)](system.windows.forms.control.ontextchanged#system-windows-forms-control-ontextchanged%28system-eventargs%29) | 引发 [TextChanged](system.windows.forms.control.textchanged#system-windows-forms-control-textchanged) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnValidated(EventArgs)](system.windows.forms.control.onvalidated#system-windows-forms-control-onvalidated%28system-eventargs%29) | 引发 [Validated](system.windows.forms.control.validated#system-windows-forms-control-validated) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnValidating(CancelEventArgs)](system.windows.forms.control.onvalidating#system-windows-forms-control-onvalidating%28system-componentmodel-canceleventargs%29) | 引发 [Validating](system.windows.forms.control.validating#system-windows-forms-control-validating) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [OnVisibleChanged(EventArgs)](system.windows.forms.scrollablecontrol.onvisiblechanged#system-windows-forms-scrollablecontrol-onvisiblechanged%28system-eventargs%29) | 引发 [VisibleChanged](system.windows.forms.control.visiblechanged#system-windows-forms-control-visiblechanged) 事件。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [PerformLayout()](system.windows.forms.control.performlayout#system-windows-forms-control-performlayout) | 强制控件将布局逻辑应用于其所有子控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [PerformLayout(Control, String)](system.windows.forms.control.performlayout#system-windows-forms-control-performlayout%28system-windows-forms-control-system-string%29) | 强制控件将布局逻辑应用于其所有子控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [PointToClient(Point)](system.windows.forms.control.pointtoclient#system-windows-forms-control-pointtoclient%28system-drawing-point%29) | 将指定屏幕点的位置计算为客户端坐标。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [PointToScreen(Point)](system.windows.forms.control.pointtoscreen#system-windows-forms-control-pointtoscreen%28system-drawing-point%29) | 将指定客户端点的位置计算为屏幕坐标。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [PreProcessControlMessage(Message)](system.windows.forms.control.preprocesscontrolmessage#system-windows-forms-control-preprocesscontrolmessage%28system-windows-forms-message@%29) | 在调度键盘或输入消息之前，预处理消息循环中的键盘或输入消息。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [PreProcessMessage(Message)](system.windows.forms.control.preprocessmessage#system-windows-forms-control-preprocessmessage%28system-windows-forms-message@%29) | 在调度键盘或输入消息之前，预处理消息循环中的键盘或输入消息。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ProcessCmdKey(Message, Keys)](system.windows.forms.control.processcmdkey#system-windows-forms-control-processcmdkey%28system-windows-forms-message@-system-windows-forms-keys%29) | 处理命令键。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ProcessDialogChar(Char)](system.windows.forms.control.processdialogchar#system-windows-forms-control-processdialogchar%28system-char%29) | 处理对话字符。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ProcessDialogKey(Keys)](system.windows.forms.control.processdialogkey#system-windows-forms-control-processdialogkey%28system-windows-forms-keys%29) | 处理对话键。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ProcessKeyEventArgs(Message)](system.windows.forms.control.processkeyeventargs#system-windows-forms-control-processkeyeventargs%28system-windows-forms-message@%29) | 处理键消息并生成相应的控制事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ProcessKeyMessage(Message)](system.windows.forms.control.processkeymessage#system-windows-forms-control-processkeymessage%28system-windows-forms-message@%29) | 处理键盘消息。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ProcessKeyPreview(Message)](system.windows.forms.control.processkeypreview#system-windows-forms-control-processkeypreview%28system-windows-forms-message@%29) | 预览键盘消息。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ProcessMnemonic(Char)](system.windows.forms.control.processmnemonic#system-windows-forms-control-processmnemonic%28system-char%29) | 处理助记字符。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RaiseDragEvent(Object, DragEventArgs)](system.windows.forms.control.raisedragevent#system-windows-forms-control-raisedragevent%28system-object-system-windows-forms-drageventargs%29) | 引发适当的拖动事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RaiseKeyEvent(Object, KeyEventArgs)](system.windows.forms.control.raisekeyevent#system-windows-forms-control-raisekeyevent%28system-object-system-windows-forms-keyeventargs%29) | 引发相应的键事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RaiseMouseEvent(Object, MouseEventArgs)](system.windows.forms.control.raisemouseevent#system-windows-forms-control-raisemouseevent%28system-object-system-windows-forms-mouseeventargs%29) | 引发相应的鼠标事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RaisePaintEvent(Object, PaintEventArgs)](system.windows.forms.control.raisepaintevent#system-windows-forms-control-raisepaintevent%28system-object-system-windows-forms-painteventargs%29) | 引发适当的画图事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RecreateHandle()](system.windows.forms.control.recreatehandle#system-windows-forms-control-recreatehandle) | 强制重新创建控件的句柄。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RectangleToClient(Rectangle)](system.windows.forms.control.rectangletoclient#system-windows-forms-control-rectangletoclient%28system-drawing-rectangle%29) | 计算客户端坐标中指定屏幕矩形的大小和位置。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RectangleToScreen(Rectangle)](system.windows.forms.control.rectangletoscreen#system-windows-forms-control-rectangletoscreen%28system-drawing-rectangle%29) | 计算屏幕坐标中指定客户端矩形的大小和位置。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Refresh()](system.windows.forms.control.refresh#system-windows-forms-control-refresh) | 强制控件使其工作区失效，并立即重新绘制自身和任何子控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RescaleConstantsForDpi(Int32, Int32)](system.windows.forms.control.rescaleconstantsfordpi#system-windows-forms-control-rescaleconstantsfordpi%28system-int32-system-int32%29) | 提供常量，用于在发生 DPI 更改时重新缩放控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResetBackColor()](system.windows.forms.control.resetbackcolor#system-windows-forms-control-resetbackcolor) | 将 [BackColor](system.windows.forms.control.backcolor#system-windows-forms-control-backcolor) 属性重置为其默认值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResetBindings()](system.windows.forms.control.resetbindings#system-windows-forms-control-resetbindings) | 使绑定到 [BindingSource](system.windows.forms.bindingsource) 控件的控件重新读取列表中的所有项并刷新其显示的值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResetCursor()](system.windows.forms.control.resetcursor#system-windows-forms-control-resetcursor) | 将 [Cursor](system.windows.forms.control.cursor#system-windows-forms-control-cursor) 属性重置为其默认值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResetFont()](system.windows.forms.control.resetfont#system-windows-forms-control-resetfont) | 将 [Font](system.windows.forms.control.font#system-windows-forms-control-font) 属性重置为其默认值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResetForeColor()](system.windows.forms.control.resetforecolor#system-windows-forms-control-resetforecolor) | 将 [ForeColor](system.windows.forms.control.forecolor#system-windows-forms-control-forecolor) 属性重置为其默认值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResetImeMode()](system.windows.forms.control.resetimemode#system-windows-forms-control-resetimemode) | 将 [ImeMode](system.windows.forms.control.imemode#system-windows-forms-control-imemode) 属性重置为其默认值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResetMouseEventArgs()](system.windows.forms.control.resetmouseeventargs#system-windows-forms-control-resetmouseeventargs) | 重置控件以处理 [MouseLeave](system.windows.forms.control.mouseleave#system-windows-forms-control-mouseleave) 事件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResetRightToLeft()](system.windows.forms.control.resetrighttoleft#system-windows-forms-control-resetrighttoleft) | 将 [RightToLeft](system.windows.forms.control.righttoleft#system-windows-forms-control-righttoleft) 属性重置为其默认值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResetText()](system.windows.forms.control.resettext#system-windows-forms-control-resettext) | 将 [Text](system.windows.forms.control.text#system-windows-forms-control-text) 属性重置为其默认值（[Empty](system.string.empty#system-string-empty)）。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResumeLayout()](system.windows.forms.control.resumelayout#system-windows-forms-control-resumelayout) | 恢复通常的布局逻辑。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ResumeLayout(Boolean)](system.windows.forms.control.resumelayout#system-windows-forms-control-resumelayout%28system-boolean%29) | 恢复通常的布局逻辑，可以选择强制立即布局挂起的布局请求。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RtlTranslateAlignment(ContentAlignment)](system.windows.forms.control.rtltranslatealignment#system-windows-forms-control-rtltranslatealignment%28system-drawing-contentalignment%29) | 将指定的 [ContentAlignment](system.drawing.contentalignment) 值转换为适当的 [ContentAlignment](system.drawing.contentalignment) 值，以支持从右到左的文本。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RtlTranslateAlignment(HorizontalAlignment)](system.windows.forms.control.rtltranslatealignment#system-windows-forms-control-rtltranslatealignment%28system-windows-forms-horizontalalignment%29) | 将指定的 [HorizontalAlignment](system.windows.forms.horizontalalignment) 值转换为适当的 [HorizontalAlignment](system.windows.forms.horizontalalignment) 值，以支持从右到左的文本。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RtlTranslateAlignment(LeftRightAlignment)](system.windows.forms.control.rtltranslatealignment#system-windows-forms-control-rtltranslatealignment%28system-windows-forms-leftrightalignment%29) | 将指定的 [LeftRightAlignment](system.windows.forms.leftrightalignment) 值转换为适当的 [LeftRightAlignment](system.windows.forms.leftrightalignment) 值，以支持从右到左的文本。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RtlTranslateContent(ContentAlignment)](system.windows.forms.control.rtltranslatecontent#system-windows-forms-control-rtltranslatecontent%28system-drawing-contentalignment%29) | 将指定的 [ContentAlignment](system.drawing.contentalignment) 值转换为适当的 [ContentAlignment](system.drawing.contentalignment) 值，以支持从右到左的文本。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RtlTranslateHorizontal(HorizontalAlignment)](system.windows.forms.control.rtltranslatehorizontal#system-windows-forms-control-rtltranslatehorizontal%28system-windows-forms-horizontalalignment%29) | 将指定的 [HorizontalAlignment](system.windows.forms.horizontalalignment) 值转换为适当的 [HorizontalAlignment](system.windows.forms.horizontalalignment) 值，以支持从右到左的文本。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [RtlTranslateLeftRight(LeftRightAlignment)](system.windows.forms.control.rtltranslateleftright#system-windows-forms-control-rtltranslateleftright%28system-windows-forms-leftrightalignment%29) | 将指定的 [LeftRightAlignment](system.windows.forms.leftrightalignment) 值转换为适当的 [LeftRightAlignment](system.windows.forms.leftrightalignment) 值，以支持从右到左的文本。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Scale(Single, Single)](system.windows.forms.control.scale#system-windows-forms-control-scale%28system-single-system-single%29) | ::: moniker range=" netframework-2.0 netframework-3.0 netframework-3.5 netframework-4.0 netframework-4.5 netframework-4.5.1 netframework-4.5.2 netframework-4.6 netframework-4.6.1 netframework-4.6.2 netframework-4.7 netframework-4.7.1 netframework-4.7.2 netframework-4.8 netframework-4.8.1 windowsdesktop-3.0 windowsdesktop-3.1 windowsdesktop-5.0 "<br>**已过时.**<br><br>::: moniker-end<br><br>::: moniker range=" windowsdesktop-10.0 windowsdesktop-11.0 windowsdesktop-6.0 windowsdesktop-7.0 windowsdesktop-8.0 windowsdesktop-9.0 "<br>**已过时.**<br><br>::: moniker-end<br><br>缩放整个控件和任何子控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Scale(Single)](system.windows.forms.control.scale#system-windows-forms-control-scale%28system-single%29) | ::: moniker range=" netframework-2.0 netframework-3.0 netframework-3.5 netframework-4.0 netframework-4.5 netframework-4.5.1 netframework-4.5.2 netframework-4.6 netframework-4.6.1 netframework-4.6.2 netframework-4.7 netframework-4.7.1 netframework-4.7.2 netframework-4.8 netframework-4.8.1 windowsdesktop-3.0 windowsdesktop-3.1 windowsdesktop-5.0 "<br>**已过时.**<br><br>::: moniker-end<br><br>::: moniker range=" windowsdesktop-10.0 windowsdesktop-11.0 windowsdesktop-6.0 windowsdesktop-7.0 windowsdesktop-8.0 windowsdesktop-9.0 "<br>**已过时.**<br><br>::: moniker-end<br><br>缩放控件和任何子控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Scale(SizeF)](system.windows.forms.control.scale#system-windows-forms-control-scale%28system-drawing-sizef%29) | 按指定的缩放因子缩放控件和所有子控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ScaleBitmapLogicalToDevice(Bitmap)](system.windows.forms.control.scalebitmaplogicaltodevice#system-windows-forms-control-scalebitmaplogicaltodevice%28system-drawing-bitmap@%29) | 当发生 DPI 更改时，将逻辑位图值缩放为其等效的设备单位值。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ScaleControl(SizeF, BoundsSpecified)](system.windows.forms.scrollablecontrol.scalecontrol#system-windows-forms-scrollablecontrol-scalecontrol%28system-drawing-sizef-system-windows-forms-boundsspecified%29) | 缩放控件的位置、大小、填充和边距。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [ScaleCore(Single, Single)](system.windows.forms.scrollablecontrol.scalecore#system-windows-forms-scrollablecontrol-scalecore%28system-single-system-single%29) | 此方法与此类无关。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [ScrollControlIntoView(Control)](system.windows.forms.scrollablecontrol.scrollcontrolintoview#system-windows-forms-scrollablecontrol-scrollcontrolintoview%28system-windows-forms-control%29) | 将指定的子控件滚动到启用自动滚动的控件上的视图中。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [ScrollToControl(Control)](system.windows.forms.scrollablecontrol.scrolltocontrol#system-windows-forms-scrollablecontrol-scrolltocontrol%28system-windows-forms-control%29) | 计算指定子控件的滚动偏移量。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [Select()](system.windows.forms.control.select#system-windows-forms-control-select) | 激活控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Select(Boolean, Boolean)](system.windows.forms.control.select#system-windows-forms-control-select%28system-boolean-system-boolean%29) | 激活子控件。 （可选）指定要从中选择控件的 Tab 键顺序中的方向。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SelectNextControl(Control, Boolean, Boolean, Boolean, Boolean)](system.windows.forms.control.selectnextcontrol#system-windows-forms-control-selectnextcontrol%28system-windows-forms-control-system-boolean-system-boolean-system-boolean-system-boolean%29) | 激活下一个控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SendToBack()](system.windows.forms.control.sendtoback#system-windows-forms-control-sendtoback) | 将控件发送到 z 顺序的后面。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SetAutoScrollMargin(Int32, Int32)](system.windows.forms.scrollablecontrol.setautoscrollmargin#system-windows-forms-scrollablecontrol-setautoscrollmargin%28system-int32-system-int32%29) | 设置自动滚动边距的大小。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [SetAutoSizeMode(AutoSizeMode)](system.windows.forms.control.setautosizemode#system-windows-forms-control-setautosizemode%28system-windows-forms-autosizemode%29) | 设置一个值，该值指示控件在启用控件 [AutoSize](system.windows.forms.control.autosize#system-windows-forms-control-autosize) 属性时的行为方式。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SetBounds(Int32, Int32, Int32, Int32, BoundsSpecified)](system.windows.forms.control.setbounds#system-windows-forms-control-setbounds%28system-int32-system-int32-system-int32-system-int32-system-windows-forms-boundsspecified%29) | 将控件的指定边界设置为指定的位置和大小。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SetBounds(Int32, Int32, Int32, Int32)](system.windows.forms.control.setbounds#system-windows-forms-control-setbounds%28system-int32-system-int32-system-int32-system-int32%29) | 将控件的边界设置为指定的位置和大小。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SetBoundsCore(Int32, Int32, Int32, Int32, BoundsSpecified)](system.windows.forms.control.setboundscore#system-windows-forms-control-setboundscore%28system-int32-system-int32-system-int32-system-int32-system-windows-forms-boundsspecified%29) | 执行设置此控件的指定边界的工作。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SetClientSizeCore(Int32, Int32)](system.windows.forms.control.setclientsizecore#system-windows-forms-control-setclientsizecore%28system-int32-system-int32%29) | 设置控件的工作区的大小。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SetDisplayRectLocation(Int32, Int32)](system.windows.forms.scrollablecontrol.setdisplayrectlocation#system-windows-forms-scrollablecontrol-setdisplayrectlocation%28system-int32-system-int32%29) | 将显示窗口定位到指定的值。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [SetScrollState(Int32, Boolean)](system.windows.forms.scrollablecontrol.setscrollstate#system-windows-forms-scrollablecontrol-setscrollstate%28system-int32-system-boolean%29) | 设置指定的滚动状态标志。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |
| [SetStyle(ControlStyles, Boolean)](system.windows.forms.control.setstyle#system-windows-forms-control-setstyle%28system-windows-forms-controlstyles-system-boolean%29) | 将指定的 [ControlStyles](system.windows.forms.controlstyles) 标志设置为或 `true``false`。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SetTopLevel(Boolean)](system.windows.forms.control.settoplevel#system-windows-forms-control-settoplevel%28system-boolean%29) | 将控件设置为顶级控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SetVisibleCore(Boolean)](system.windows.forms.control.setvisiblecore#system-windows-forms-control-setvisiblecore%28system-boolean%29) | 将控件设置为指定的可见状态。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [Show()](system.windows.forms.control.show#system-windows-forms-control-show) | 向用户显示控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SizeFromClientSize(Size)](system.windows.forms.control.sizefromclientsize#system-windows-forms-control-sizefromclientsize%28system-drawing-size%29) | 从工作区的高度和宽度确定整个控件的大小。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [SuspendLayout()](system.windows.forms.control.suspendlayout#system-windows-forms-control-suspendlayout) | 暂时挂起控件的布局逻辑。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [ToString()](system.windows.forms.panel.tostring#system-windows-forms-panel-tostring) | 返回此控件的字符串表示形式。 |  |
| [Update()](system.windows.forms.control.update#system-windows-forms-control-update) | 使控件在其工作区内重新绘制无效区域。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [UpdateBounds()](system.windows.forms.control.updatebounds#system-windows-forms-control-updatebounds) | 使用当前大小和位置更新控件的边界。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32)](system.windows.forms.control.updatebounds#system-windows-forms-control-updatebounds%28system-int32-system-int32-system-int32-system-int32-system-int32-system-int32%29) | 使用指定的大小、位置和客户端大小更新控件的边界。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [UpdateBounds(Int32, Int32, Int32, Int32)](system.windows.forms.control.updatebounds#system-windows-forms-control-updatebounds%28system-int32-system-int32-system-int32-system-int32%29) | 使用指定的大小和位置更新控件的边界。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [UpdateStyles()](system.windows.forms.control.updatestyles#system-windows-forms-control-updatestyles) | 强制将分配的样式重新应用于控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [UpdateZOrder()](system.windows.forms.control.updatezorder#system-windows-forms-control-updatezorder) | 按父级的 z 顺序更新控件。<br> (继承自 [Control](system.windows.forms.control)) |  |
| [WndProc(Message)](system.windows.forms.scrollablecontrol.wndproc#system-windows-forms-scrollablecontrol-wndproc%28system-windows-forms-message@%29) | 处理 Windows 消息。<br> (继承自 [ScrollableControl](system.windows.forms.scrollablecontrol)) |  |